//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeSiteWithMvc.Models.entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblDeneyimlerim
    {
        public int ıd { get; set; }
        [Required(ErrorMessage ="Lürfen Bu Alanı Doldurunuz..")]
        public string baslik { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alanı Doldurunuz..")]
        public string altBaslik { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alanı Doldurunuz..")]
        public string aciklama { get; set; }
        public string tarih { get; set; }
    }
}
