//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeSiteWithMvc.Models.entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblHakkimda
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string ad { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string soyad { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string adres { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string telefon { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string mail { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string aciklama { get; set; }
        public string fotograf { get; set; }
    }
}
