//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeSiteWithMvc.Models.entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblSocialMedia
    {
        public int id { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string sosyalMedyaLink { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string iconLink { get; set; }
        [Required(ErrorMessage = "Lürfen Bu Alaný Doldurunuz..")]
        public string sosyalMedyaAd { get; set; }
    }
}
